name: 'CI'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  pgbelt_ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build pgbelt Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: autodesk/pgbelt:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build Postgres Image with pglogical
        uses: docker/build-push-action@v6
        with:
          context: tests/integration/files/postgres17-pglogical-docker
          push: false
          load: true
          tags: autodesk/postgres-pglogical-docker:17
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Run flake8
        run: docker compose run flake8
      - name: Python Black
        run: docker compose run black
      - name: Pytest
        run: docker compose run tests
      # This ugly bit is necessary if you don't want your cache to grow forever
      # until it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
